name: Devops_CI/CD

on:
  workflow_dispatch:
    # Optional: You can add inputs here if you need to pass variables
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'qa'
        
        #this one for automate when main branch marge
  # pull_request:
  #   branches: [main]
  #   types: [closed]

concurrency:
  group: deploy
  cancel-in-progress: true

env:
  BASE_DIR: /home/ubuntu/demo
  REPO_DIR: /home/ubuntu/demo/testing_git_hub
  REPO_URL: https://github.com/ajinkya2304/testing_git_hub.git

jobs:
  deploy:
    timeout-minutes: 10
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, qa]

    steps:
      - name: Setup workspace
        run: |
          set -e
          mkdir -p "$BASE_DIR"
          if [ ! -d "$REPO_DIR/.git" ]; then
            if [ -d "/home/ubuntu/.npm" ] || [ -d "/home/ubuntu/.pm2" ]; then
              echo "Cleaning npm and pm2 cache..."
             rm -rf /home/ubuntu/.npm/ /home/ubuntu/.pm2/
            fi
            echo "Cloning repo..."
            git clone "$REPO_URL" "$REPO_DIR"
            cd "$REPO_DIR"
            sudo apt-get update
            sudo apt install -y nodejs npm
          else
            echo "Updating repo..."
            cd "$REPO_DIR"
            git fetch origin
            git checkout -B main origin/main
            git reset --hard origin/main
            git clean -fd
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # - name: Install dependencies
      #   run: |
      #     set -e
      #     cd "$REPO_DIR"
      #     sudo npm install
      #     sudo npm install -g pm2
      #     pm2 start ecosystem.config.js
      
      # - name: validation
      #   run: |
      #     set -e
      #     cd "$REPO_DIR"
      #     pm2 list
      #     pm2 logs





