name: Devops_CI/CD

on:
  pull_request:
    branches: [main]
    types: [closed]

env:
  BASE_DIR: /home/ubuntu/demo
  REPO_DIR: /home/ubuntu/demo/testing_git_hub
  REPO_URL: https://github.com/ajinkya2304/testing_git_hub.git

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, qa]

    steps:
      - name: Setup workspace
        run: |
          set -e
          mkdir -p "$BASE_DIR"
          if [ ! -d "$REPO_DIR/.git" ]; then
            echo "Cloning repo..."
            git clone "$REPO_URL" "$REPO_DIR"
            sudo apt-get update
            sudo apt install -y nodejs npm
            npm install -g pm2
          else
            echo "Updating repo..."
            cd "$REPO_DIR"
            git fetch origin
            git checkout -B main origin/main
            git reset --hard origin/main
            git clean -fd
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          set -e
          cd "$REPO_DIR"
          npm install
          pm2 reload demo-app 

      - name: verfication app
        run: |
          pm2 list
          pm2 logs 
          curl http://localhost:3000




